baseURL = "https://albertomoreno-dev.github.io/my_lauchx_blog/"
languageCode = "en-us"
title = "Bitácora de Viaje de AlbertoMoreno"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquí pon tu twitter 👇
  twitter_handle = "@AlbertoMore"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
